title: "Alen Abd Data Science Portfolio"
description: "A collection of data science projects and analyses"

# Site settings
repository: "alenabd24/alenabd24.github.io"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# Minimal Mistakes theme settings
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      share: true
      read_time: true
      comments: false
      sidebar:
        nav: "main"
