title: "Alen Abd Data Science Portfolio"
description: "A collection of data science projects and analyses"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
